<a href="https://colab.research.google.com/github/bahaeddine-toumi/LSTM-Email-Classification/blob/main/Sentiment_analyses_Email_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fake News Classifier Using LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#

In [2]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df = pd.read_excel('/content/drive/MyDrive/Email_Final.xlsx')


In [4]:
df.head()

Body  Label
0  Continental has a price of $297.17(non-refunda...      1
1  Attached is the final notification report for ...      1
2   The basic reason we are changing meters in Si...      1
3  We are going to try to get to the point of upl...      1
4  Please open the attachment and send me your in...      1

In [5]:
###Drop Nan Values
df=df.dropna()


In [6]:
## Get the Independent Features

X=df.drop('Label',axis=1)

In [8]:
## Get the Dependent features
y=df['Label']

In [9]:
X.shape

(36782, 1)

In [10]:
y.shape

(36782,)

In [11]:
import tensorflow as tf

In [12]:
tf.__version__

'2.8.2'

In [13]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [14]:
### Vocabulary size
voc_size=5000

### Onehot Representation

In [15]:
messages=X.copy()

In [17]:
messages['Body'][1]

'Attached is the final notification report for January, 2002. Click below, then click FETCH to view. http:nahou-dmagn01penalivelink.exe?funcll.loginusernameGCPGuestpasswordnextURL%2fena%2flivelink.exe?funcll%26objId965334objActionbrowsesortname Documents should be available for review on Friday, Feb 1, 2002. Shortname changes will be coordinated wERMS IT on Friday, Feb 1, 2002. Records will be inactivated on Friday, Feb 1, 2002. Please call with any questions or concerns. Cheryl Johnson Enron Net Works Global Data Management 713.853.3103'

In [18]:
messages.reset_index(inplace=True)

In [19]:
import nltk
import re
from nltk.corpus import stopwords

In [20]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [22]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['Body'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [23]:
corpus

['continent price non refund follow roundtrip flight depart houston nov pm pm depart chicago nov pm unit price non refund follow roundtrip flight depart houston nov pm pm pm pm depart chicago nov pm let know decid thank irena hogan sr administr assist enron america',
 'attach final notif report januari click click fetch view http nahou dmagn penalivelink exe funcll loginusernamegcpguestpasswordnexturl fena flivelink exe funcll objid objactionbrowsesortnam document avail review friday feb shortnam chang coordin werm friday feb record inactiv friday feb pleas call question concern cheryl johnson enron net work global data manag',
 'basic reason chang meter sitara pglc origin set meter set use name pipelin call e ngpl ngpl meter number pglc meter number pglc meter number pglcngpl reason everyth correctli reflect upload nom pegasi meter number pglc specif use product place novemb pglc nbplmanhattan buy northern border specif ga take pglc nbplpeopl manhattan transfer point meter bounc ticke

In [24]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[989,
  4559,
  2026,
  1927,
  3119,
  465,
  516,
  859,
  1846,
  2491,
  3370,
  3370,
  859,
  1397,
  2491,
  3370,
  979,
  4559,
  2026,
  1927,
  3119,
  465,
  516,
  859,
  1846,
  2491,
  3370,
  3370,
  3370,
  3370,
  859,
  1397,
  2491,
  3370,
  1502,
  686,
  2790,
  1250,
  3182,
  4257,
  3447,
  2131,
  3529,
  4423,
  4108],
 [4557,
  4770,
  1493,
  116,
  4000,
  150,
  150,
  3571,
  2667,
  4529,
  3527,
  4793,
  4577,
  2018,
  4809,
  1711,
  4059,
  4586,
  2018,
  4809,
  2959,
  3886,
  2458,
  3891,
  1427,
  4948,
  4111,
  4393,
  2144,
  4809,
  388,
  4948,
  4111,
  1263,
  2021,
  4948,
  4111,
  3325,
  304,
  2220,
  1902,
  2763,
  4121,
  4423,
  884,
  1998,
  1547,
  1642,
  4970],
 [4797,
  67,
  2144,
  1039,
  3155,
  3295,
  1347,
  4364,
  1039,
  4364,
  2426,
  1579,
  1312,
  304,
  3605,
  3912,
  3912,
  1039,
  2218,
  3295,
  1039,
  2218,
  3295,
  1039,
  2218,
  1998,
  67,
  2984,
  2473,
  2050,
  2360,
  3886,
  215,
  103

In [26]:
li = [4524,
  2000,
  1296,
  2617,
  1612,
  1634,
  1427,
  3987,
  3325,
  99,
  310,
  4557,
  4191,
  345,
  55,
  1484,
  1281,
  4518,
  4705,
  304,
  2218,
  4375,
  3325,
  3361,
  2411,
  304,
  1544,
  3168,
  960,
  3989,
  4460,
  2218,
  304,
  3325,
  3361,
  1612,
  3294,
  55,
  1785,
  3227,
  3325,
  3031,
  3989,
  1712,
  2746,
  616,
  1105,
  4375,
  2220,
  2136,
  1250,
  3149]
len(li)

52

### Embedding Representation

In [45]:
sent_length=190
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 3529 4423 4108]
 [   0    0    0 ... 1547 1642 4970]
 [   0    0    0 ...  238 1250 1650]
 ...
 [   0    0    0 ... 1250 4684 3816]
 [ 170 4333  803 ... 3334  599  294]
 [ 170 4333  803 ... 3334  599  294]]


In [46]:
embedded_docs[-1]

array([ 170, 4333,  803, 2679, 1381, 2621, 4061, 3597, 2778, 4120, 4037,
       2778, 3119, 1533, 1657,  197, 4478, 1639, 2778, 2359,  989, 4789,
       3864, 3705, 1707,  304, 1629,  871, 4333, 4582, 4333, 1270, 3315,
        144, 1547, 1639, 4698, 1381, 3415, 4685, 3728, 2662, 4843,  293,
       3535, 1930, 4582, 2468,  197, 1143, 4118, 4240, 2035, 4333, 2000,
       3817, 1639, 4651,  392, 4959, 2789,  591, 4929, 1218, 2255, 4739,
       2116, 2541, 1737, 2104, 3446,   99, 1737, 4445, 3963, 4566, 2324,
       1209, 2719, 2140,  878,  782,  803, 1966, 3963, 4588, 1569, 4099,
       2000, 2676, 1569, 1966, 4848,  462, 4333, 3435,  487, 2034, 2719,
       1201,  803, 1966, 2777, 3415, 4020, 2926, 3991, 1966, 4705, 4020,
       2926, 3812, 4863, 2101,   87, 3090, 1243, 3144,  812, 1647, 1616,
       1785, 4872,  782, 1783, 2134, 3497, 2149,  878,  782, 2059, 1466,
       3029, 3901,  878,  922, 2420,  150, 1379, 4406, 2144, 1780, 2000,
       4476, 2218,  726, 2104, 1780, 2000, 1667, 35

In [49]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 190, 40)           200000    
                                                                 
 lstm_2 (LSTM)               (None, 100)               56400     
                                                                 
 dense_2 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [50]:
len(embedded_docs),y.shape

(36782, (36782,))

In [51]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [52]:
X_final.shape,y_final.shape

((36782, 190), (36782,))

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [54]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=15,batch_size=64)

Epoch 1/10
386/386 [==============================] - 93s 235ms/step - loss: 0.4800 - accuracy: 0.7659 - val_loss: 0.4042 - val_accuracy: 0.8253
Epoch 2/10
386/386 [==============================] - 89s 231ms/step - loss: 0.2922 - accuracy: 0.8823 - val_loss: 0.3175 - val_accuracy: 0.8696
Epoch 3/10
386/386 [==============================] - 89s 230ms/step - loss: 0.2450 - accuracy: 0.9054 - val_loss: 0.3078 - val_accuracy: 0.8774
Epoch 4/10
386/386 [==============================] - 89s 230ms/step - loss: 0.1946 - accuracy: 0.9253 - val_loss: 0.3090 - val_accuracy: 0.8795
Epoch 5/10
386/386 [==============================] - 89s 231ms/step - loss: 0.1636 - accuracy: 0.9407 - val_loss: 0.3157 - val_accuracy: 0.8886
Epoch 6/10
386/386 [==============================] - 89s 230ms/step - loss: 0.1373 - accuracy: 0.9510 - val_loss: 0.3306 - val_accuracy: 0.8875
Epoch 7/10
386/386 [==============================] - 88s 229ms/step - loss: 0.1150 - accuracy: 0.9609 - val_loss: 0.3540 - val_ac

### Adding Dropout 

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Performance Metrics And Accuracy

In [61]:
y_pred=model.predict(X_test)

AttributeError: ignored

In [87]:
predict =[]
for i in range(y_pred.shape[0]):
  if (y_pred[i][0]>0.5):
    predict.append(1)
  else :
    predict.append(0)

In [88]:
predict =np.array(predict)


In [89]:
predict.shape

(12139,)

In [75]:
y_test.shape

(12139,)

In [56]:
from sklearn.metrics import confusion_matrix

In [90]:
confusion_matrix(y_test,predict)

array([[5038,  486],
       [ 832, 5783]])

In [92]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predict)

0.8914243347886975